FROM python:3.9-slim
# Install gRPC tools
RUN python3 -m pip install grpcio-tools

RUN pip install --upgrade protobuf

# RUN pip install opencv-python

# RUN apt-get update \
#     && apt-get install -y libgl1-mesa-glx libglib2.0-0 \
#     && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# COPY requirements.txt requirements.txt
# RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# CMD ["python3", "./Server/ImageClient.py"]