FROM python:3.9-slim
# Install gRPC tools
RUN python3 -m pip install grpcio-tools

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["python", "./Server/ImageClient.py"]