FROM python:3.9-slim

# Install gRPC tools
RUN python3 -m pip install grpcio-tools

RUN pip install --upgrade protobuf

WORKDIR /app

# COPY requirements.txt requirements.txt
# RUN pip install --no-cache-dir -r requirements.txt

# COPY images /app/images
# COPY Server ./Server/
COPY . .

CMD ["python3", "./Server/ImageServer.py"]